//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CropAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_DETAILS
    {
        public Nullable<int> User_ID { get; set; }
        public string Acc_Num { get; set; }
        public string Acc_HolderName { get; set; }
        public int IFSC_Code { get; set; }
        public string BankingName { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
